name: kubernetes-stig-baseline
title: Kubernetes Security Technical Implementation Guide
maintainer: VMTA
copyright: The Authors
copyright_email: stigs@broadcom.com
license: Apache-2.0
summary: "This Security Technical Implementation Guide is published as a tool to improve the security of Department of Defense (DoD) information systems. The requirements are derived from the National Institute of Standards and Technology (NIST) 800-53 and related documents. Comments or proposed revisions to this document should be sent via email to the following address: disa.stig_spt@mail.mil."
version: 1.0.11

supports:
  - platform-family: linux

inputs:
  - name: manifests_path
    description: 'Path to Kubernetes manifest files on the target node'
    type: string
    value: '/etc/kubernetes/manifests'
    required: true

  - name: pki_path
    description: 'Path to Kubernetes PKI files on the target node'
    type: string
    value: '/etc/kubernetes/pki'
    required: true

  - name: kubeadm_conf_path
    description: 'Path to kubeadm conf file on the target node'
    type: string
    value: '/etc/systemd/system/kubelet.service'
    required: true

  - name: kubectl_path
    description: 'Path to kubectl on the target node'
    type: string
    value: '/usr/local/bin/kubectl'
    required: true

  - name: kubectl_minversion
    description: 'Minimum version of the kubectl binary on the target node'
    type: string
    value: 'v1.20.11'
    required: true

  - name: kubernetes_conf_files
    description: 'Path to Kubernetes conf files on the target node'
    type: array
    value:
        - /etc/kubernetes/admin.conf
        - /etc/kubernetes/scheduler.conf
        - /etc/kubernetes/controller-manager.conf
    required: true

  - name: kubectl_conf_path
    description: 'Path to kubectl conf file to use for running commands'
    type: string
    value: '/etc/kubernetes/admin.conf'
    required: true

  - name: kubelet_process
    description: 'Some systems may have multiple processes named kubelet running with one as a watchdog. Specify the path to kubelet in this case. Defaults to /usr/bin/kubelet'
    type: string
    value: '/usr/bin/kubelet'
    required: true

  - name: kubelet_conf_path
    description: 'Path to kubelet config file to use for running commands. Needed mostly if there are multiple kubelet processes as the resource doesnt handle that well.'
    type: string
    value: ''
    required: false

  - name: kubelet_kubeconf_path
    description: 'Path to kubelet conf file to use for running commands. Needed mostly if there are multiple kubelet processes as the resource doesnt handle that well.'
    type: string
    value: ''
    required: false

  - name: k8s_min_supported_version
    description: 'Latest version of Kubernetes to test for supported version. Currently K8s maintains the most recent 3 minor branches. For example if 1.22.5 is the latest release then put the most recent 1.20.y version here.'
    type: string
    value: 'v1.24.12'
    required: true

  - name: approved_cipher_suites
    description: 'Array of approved cipher suites for TLS'
    type: array
    value:
      - 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
      - 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'
      - 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'
      - 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256'
    required: true

  - name: pod_security_admission_namespace_exemptions
    description: 'Array of namespaces that are exempted in pod security admission policy.'
    type: array
    value: []
    required: true

  - name: pod_security_admission_user_exemptions
    description: 'Array of usernames that are exempted in pod security admission policy.'
    type: array
    value: []
    required: true

  - name: pod_security_admission_runtime_exemptions
    description: 'Array of runtime classes that are exempted in pod security admission policy.'
    type: array
    value: []
    required: true
